### ISSUE TITLE
Terraform Azurerm AKS documentation pages load extremely slow

### ISSUE THREAD

**Issue by bborovan** [Azure/terraform-azurerm-aks#407] opened 2023-07-06 12:35 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Hello,

This is with regards to your Terraform documentation page and no specific category I could file this under here, so setting as a feature request to get this on your radar.

I wrote with Hashicorp support to notify them about this and the suggested to reach out to you with a ticket, as is not managed by them apparently.

Specifically, the https://registry.terraform.io/modules/Azure/aks/azurerm/latest documentation page is taking over 1 minute to load when I visit it, and Hashicorp is seeing the same thing. At first I thought the page does not load at all since it is so excessively slow.

Hope this information helps!

Brent

### New or Affected Resource(s)/Data Source(s)

Documentation page for Azurerm AKS

**Comment by zioproto** [comment] 2023-07-06 12:42
Thanks for reporting this @bborovan 

We are aware of this issue. The problem is that the README is huge, and the page is automatically generated from the README.

**Comment by lonegunmanb** [comment] 2023-07-07 02:48
Thanks @bborovan for opening this issue, we'll see what we can do to reduce the readme file.

**Comment by zioproto** [comment] 2023-09-08 06:34
@bborovan this should be fixed now by https://github.com/Azure/terraform-azurerm-aks/pull/437

**Comment by zioproto** [comment] 2023-09-08 07:41
Keeping the issue open because the problem is not completely solved.
Idea: create an automated `variables.md` file to document the variables, without bloating the readme file.

**Comment by lonegunmanb** [comment] 2023-11-14 05:37
I'm closing this issue since we've removed spaces in markdown table, and the page can be loaded successfully now.

**Closed by lonegunmanb** 2023-11-14 05:37 UTC
