### ISSUE TITLE
Fix for public_network_access_enabled in 8.0.0 is incomplete

### ISSUE THREAD

**Issue by JaredDarling** [Azure/terraform-azurerm-aks#526] opened 2024-03-20 19:23 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Greenfield/Brownfield provisioning

brownfield

### Terraform Version

1.5.4

### Module Version

8.0.0

### AzureRM Provider Version

3.94.0

### Affected Resource(s)/Data Source(s)

azurerm_kubernetes_cluster

### Terraform Configuration Files

```hcl
any
```

### tfvars variables values

```hcl
any
```

### Debug Output/Panic Output

```shell
Warning: Deprecated attribute
│ 
│   on .terraform/modules/aks_cluster.aks_cluster/main.tf line 548, in resource "azurerm_kubernetes_cluster" "main":
│  548:       public_network_access_enabled,
│ 
│ The attribute "public_network_access_enabled" is deprecated. Refer to the provider documentation for details.
```

### Expected Behaviour

No warning

### Actual Behaviour

Warning during plan

### Steps to Reproduce

terraform plan

**Comment by zioproto** [comment] 2024-03-28 08:25
Hello. It is intentional to keep that value in the lifecycle block.

To avoid problems with existing terraform states that contain `public_network_access_enabled`.

**Comment by lonegunmanb** [comment] 2024-05-06 07:38
Hi @JaredDarling I'm closing this issue since this warning is by design, please feel free to open it if you have different thought, thank you!

**Closed by lonegunmanb** 2024-05-06 07:38 UTC
Labels: bug
