### ISSUE TITLE
Create new tags

### ISSUE THREAD

**Issue by aditya-enthu** [Azure/terraform-azurerm-aks#502] opened 2024-01-29 08:06 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Do we have plan to create tags/release for the new changes?

@jiaweitao001 

### New or Affected Resource(s)/Data Source(s)

new tags for public_network_access_enabled

### Potential Terraform Configuration

```hcl
new tags
```

**Comment by lonegunmanb** [comment] 2024-01-30 01:10
Hi @aditya-enthu thanks for opening this issue, would you please give us a briefing on your issue, along with a minimum example that could teach us how to reproduce it on our side? Thanks!

**Comment by aditya-enthu** [comment] 2024-01-30 17:43
@lonegunmanb actually this is not a issue but I was unable to figure out on how to reach the team member, thus I created this issue. I am wondering **when we plan to create tags/release for the new change?**

**Comment by aditya-enthu** [comment] 2024-02-08 21:34
@lonegunmanb @jiaweitao001  who would be able to create the new release/tag from the main branch

**Comment by lonegunmanb** [comment] 2024-02-19 06:39
Ahaa sorry for the late reply @aditya-enthu , for this module, if there's no breaking changes in the current sprint, then we'd like to release a minor version upgrade every month. We'll defer all breaking changes into one sprint, and we'd like to release a major version upgrade include all breaking changes half a year. Thus we've tried our best, but it's still a soft goal, we cannot guarantee a very accurate and stable schedule, especially when we're dealing with some complex breaking changes.

**Comment by lonegunmanb** [comment] 2024-02-20 05:37
I'm closing this issue because we're very close to `v8.0`. We'll release a new tag in this week.

**Closed by lonegunmanb** 2024-02-20 05:37 UTC
Labels: waiting-response
