### ISSUE TITLE
Support for azurerm v4

### ISSUE THREAD

**Issue by dbloquel** [Azure/terraform-azurerm-aks#597] opened 2024-10-08 14:44 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Hello 
Is ther any chance the module will be compatible with azurerm v4 ? It's been out for some times now and I did not find any reference to it here. 
Is it planned to be upgraded ? 

### New or Affected Resource(s)/Data Source(s)

provider azurerm

**Comment by Glaaj** [comment] 2024-10-11 11:59
>Is it planned to be upgraded ?

I'm currently asking myself the same question, especially since Microsoft has started the AVM collection(s).

**Comment by pcallewaert** [comment] 2024-10-15 07:06
There is pull request for this, but I see the progress is halted: https://github.com/Azure/terraform-azurerm-aks/pull/594
Is there anything that we can do to help?

**Comment by johnknutsonhc** [comment] 2024-10-21 15:37
Bump!

Anything we can do to help get #594 looked at by the maintainers? I see the acceptance tests show a failure, but it is not clear to me what the cause of the failure is.

**Comment by dada-engineer** [comment] 2024-10-23 06:12
+1

**Comment by zioproto** [comment] 2024-11-29 08:35
Hello all,

if you have a urgent need to move to azurerm v4,
my suggestion is to look into this new Microsoft AKS resource module, that is part of the [AVM initiative](https://aka.ms/avm):

https://github.com/Azure/terraform-azurerm-avm-res-containerservice-managedcluster/

This module is guaranteed to be V4 by the end of January 2025.

For the current `terraform-azurerm-aks` module, we don't have a clear plan for the upgrade.
We might come up with some instructions to migrate to the AVM module, but there is nothing decided yet.

Cc: @ibersanoMS @nellyk @lonegunmanb

**Comment by johnknutsonhc** [comment] 2024-12-01 06:22
@zioproto Will the [Azure/avm-ptn-aks-production/azurerm](https://registry.tf-registry-prod-use1.terraform.io/modules/Azure/avm-ptn-aks-production/azurerm/latest) module be updated to use the new AVM module?

**Comment by zioproto** [comment] 2024-12-02 08:27
Hello, 
* The `avm-ptn-aks-production` is an AVM **pattern** module for a specific scenario (opinionated)
* The `avm-res-containerservice-managedcluster` is an AVM **resource** module

Here more on module definitions:
https://azure.github.io/Azure-Verified-Modules/specs/shared/module-classifications/

those modules have independent lifecycles and will be both support long term.

I am not aware of a plan of consuming `avm-res-containerservice-managedcluster` inside `avm-ptn-aks-production` at the moment.

Cc: @nellyk

**Comment by zioproto** [comment] 2024-12-10 12:28
> Hi,
> 
> Does that mean that this repo will be replaced by AVM's in the future ?

Yes this is the long term vision, but we don't have a deprecation announcement for this repo yet.

**Comment by lonegunmanb** [comment] 2024-12-11 03:52
> Hi,
> 
> Does that mean that this repo will be replaced by AVM's in the future ?

As @zioproto said, this is the long term vision, but we won't deprecate this module very soon since there're many people that are still using this module. I'm closing this issue since `9.3.0` has been released and `v4` has been supported by setting `source` to `Azure/aks/azurerm//v4`. You're encouraged to use the new AVM module instead, but it's ok to continue to use this module for now.

**Closed by lonegunmanb** 2024-12-11 03:52 UTC
