### ISSUE TITLE
Undesired changes are detected during plan phase causing pods to be evicted during apply

### ISSUE THREAD

**Issue by cveld** [Azure/terraform-azurerm-aks#329] opened 2023-03-20 09:31 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Greenfield/Brownfield provisioning

greenfield

### Terraform Version

1.3.6

### Module Version

6.7.1

### AzureRM Provider Version

3.47.0

### Affected Resource(s)/Data Source(s)

azurerm_kubernetes_cluster

### Terraform Configuration Files

```hcl
module "aks" {
  source  = "Azure/aks/azurerm"
  version = "6.7.1"

  #prefix                    = "prefix-${random_id.prefix.hex}"
  prefix                    = "sandbox"
  resource_group_name       = var.resource_group_name
  kubernetes_version        = "1.24" # don't specify the patch version!
  automatic_channel_upgrade = "patch"
  network_plugin  = "azure"
  network_policy  = "azure"
  os_disk_size_gb = 60
  sku_tier        = "Paid"
  rbac_aad        = false
  vnet_subnet_id          = azurerm_subnet.aks.id
  log_analytics_workspace = azurerm_log_analytics_workspace.log_analytics_workspace
  agents_max_pods         = 100
}
```

### tfvars variables values

```hcl
N/A
```

### Debug Output/Panic Output

```shell
N/A
```

### Expected Behaviour

No changes should be present.

### Actual Behaviour

  # module.Infrastructure.module.aks.azurerm_kubernetes_cluster.main will be updated in-place
  ~ resource "azurerm_kubernetes_cluster" "main" {
        id                                  = "/subscriptions/redacted/resourceGroups/rg-bundle-test/providers/Microsoft.ContainerService/managedClusters/sandbox-aks"
      ~ kubernetes_version                  = "1.24.9" -> "1.24"
        name                                = "sandbox-aks"
        tags                                = {}
        # (27 unchanged attributes hidden)

      - microsoft_defender {
          - log_analytics_workspace_id = "/subscriptions/redacted/resourcegroups/DefaultResourceGroup-WEU/providers/Microsoft.OperationalInsights/workspaces/DefaultWorkspace-redacted-WEU" -> null
        }

        # (6 unchanged blocks hidden)
    }

### Steps to Reproduce

1. Run module and create AKS cluster
2. Run module again and see detected changes

**Comment by lonegunmanb** [comment] 2023-03-21 05:59
Hi @cveld, thanks for reporting this issue to us, I've tried the following config but cannot reproduce the same issue on my side, would you please give us a minimum example that could reproduce this issue so we can try on our side? Thanks!:

```hcl
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "rg" {
  location = "eastus"
  name     = "f-329"
}

resource "azurerm_virtual_network" "vnet" {
  name                = "f329-test-vnet"
  address_space       = ["192.168.0.0/16"]
  location            = azurerm_resource_group.rg.location
  resource_group_name = azurerm_resource_group.rg.name
}

resource "azurerm_subnet" "subnet" {
  address_prefixes     = ["192.168.0.0/24"]
  name                 = "f329-test-subnet"
  resource_group_name  = azurerm_resource_group.rg.name
  virtual_network_name = azurerm_virtual_network.vnet.name
}

# Just for demo purpose, not necessary to named cluster.
resource "azurerm_log_analytics_workspace" "main" {
  location            = azurerm_resource_group.rg.location
  name                = "prefix-workspace"
  resource_group_name = azurerm_resource_group.rg.name
  retention_in_days   = 30
  sku                 = "PerGB2018"
}

module "aks" {
  source  = "Azure/aks/azurerm"
  version = "6.7.1"

  #prefix                    = "prefix-${random_id.prefix.hex}"
  prefix                    = "sandbox"
  resource_group_name       = azurerm_resource_group.rg.name
  kubernetes_version        = "1.24" # don't specify the patch version!
  automatic_channel_upgrade = "patch"
  network_plugin            = "azure"
  network_policy            = "azure"
  os_disk_size_gb           = 60
  sku_tier                  = "Paid"
  rbac_aad                  = false
  vnet_subnet_id            = azurerm_subnet.subnet.id
  log_analytics_workspace   = azurerm_log_analytics_workspace.main
  agents_max_pods           = 100

  depends_on = [azurerm_resource_group.rg]
}
```

**Comment by zioproto** [comment] 2023-03-21 08:30
Hello @cveld 

I understand you installed AKS using the module with the variable `kubernetes_version` at the value `"1.24"` and `automatic_channel_upgrade` = `patch`.

I understand that trying to run Terraform at a later time you face an unexpected change:

```
~ kubernetes_version = "1.24.9" -> "1.24"
```

I suspect this has to do with the autoupgrade changing the AKS version while this change is not reflected in the Terraform state.

If you do:

```
az aks list -o table
```

Could you please confirm what are the values now for `KubernetesVersion` and `CurrentKubernetesVersion` for the `sandbox-aks` cluster ?

You can also check if there was any autoupgrade event from the activity logs ?

```
az monitor activity-log list --namespace Microsoft.ContainerService  --offset 72h -g <resourcegroup> -o table
```

I am afraid to reproduce the issue we must:

* Install AKS with the Terraform module
* Wait for an autoupgrade event in the patch channel
* Run Terraform again

**Comment by zioproto** [comment] 2023-03-21 08:39
I just installed AKS using `var.kubernetes_version = 1.24`, and `az aks list -o table` returns a `KubernetesVersion` of `1.24` without the patch version.

Also the Terraform state has `"kubernetes_version": "1.24",`

Now if the autoupgrade patch event changes the `KubernetesVersion` returned by the API to a value that includes the new patch version, this will conflict with the current Terraform state.

This is not a bug in the module, this should be reported in the Terraform provider.

**Comment by zioproto** [comment] 2023-03-21 08:53
@cveld regarding the `microsoft_defender` being removed. That provider option is currently not supported in the module. Is possible that you made changes to AKS in the Azure Portal and Terraform is trying to revert those changes ?

**Comment by cveld** [comment] 2023-03-21 09:39
@zioproto then I think it is due a deploy-if-not-exists policy. I can check with the Azure global admin. How can I prevent change detection for this?

**Comment by zioproto** [comment] 2023-03-21 10:08
I understand when you deploy the AKS cluster with Terraform, you have in place an Azure Policy to enable the defender profile:

https://learn.microsoft.com/en-us/azure/aks/policy-reference

![Screenshot 2023-03-21 at 11 05 58](https://user-images.githubusercontent.com/789701/226574504-47097aea-3b96-4dbf-8a97-797ec53980f2.png)

If we add the feature in this module then you would be able to specify the `microsoft_defender` in your Terraform code and you would not have any configuration drift.

Would this solve the problem for you ?

I still want to understand better also the state drift regarding the AKS version. Could you add more details also on that ?

**Comment by cveld** [comment] 2023-03-21 22:21
Policy mitigation: I am always in doubt whether you should copy DINE policy
behavior into the workload itself. This introduces double maintenance which
can get out of sync by two separate parties i.e. policy team versus
workload team. Hopefully some day terraform and DINE policies get some
handy evolution. For now I believe your proposal is the only workaround
available.

Version property: you can't replicate the behavior I experience? I deploy
1.24 and next plan it detects a change from 1.24.9 back to 1.24.

Op di 21 mrt. 2023 11:54 schreef Saverio Proto ***@***.***>:

**Comment by cveld** [comment] 2023-03-23 22:00
I ran `az aks list -o table` and interestingly the `KubernetesVersion` property got updated to 1.24.9!

Name                Location    ResourceGroup    KubernetesVersion    CurrentKubernetesVersion    ProvisioningState    Fqdn
------------------  ----------  ---------------  -------------------  --------------------------  -------------------  ------------------------------------------------
sandbox-aks         westeurope  rg-test   1.24.9               1.24.9                      Succeeded            sandbox-redacted.hcp.westeurope.azmk8s.io

**Comment by zioproto** [comment] 2023-03-24 09:32
@cveld I checked and I see that `microsoft_defender` is already supported in the module:

Variable:
https://github.com/Azure/terraform-azurerm-aks/blob/ef05b53179e878b7001d815048ac309184ad5dcc/variables.tf#L619-L624

Logic:
https://github.com/Azure/terraform-azurerm-aks/blob/ef05b53179e878b7001d815048ac309184ad5dcc/main.tf#L295-L301

Enabling the variable and configuring what is needed will now solve the problem of the Terraform state drift.

I understand the pain of having to update the Terraform code if an Azure Policy changes, but for now I dont have a better solution to address your problem.

I am opening a separate issue for the state drift regarding the Kubernetes version. I will link it here once it is open.

**Comment by zioproto** [comment] 2023-03-24 09:57
I opened https://github.com/Azure/terraform-azurerm-aks/issues/335 for the state drift problem when using the `patch` channel for autograde.

@cveld let us know if it is okay to close this issue. Thanks

**Comment by cveld** [comment] 2023-03-27 19:42
I tried to deploy with `microsoft_defender_enabled = true` but then I run in the following error:

```
╷
│ Error: Resource precondition failed
│
│   on .terraform\modules\Infrastructure.aks\main.tf line 334, in resource "azurerm_kubernetes_cluster" "main":
│  334:       condition     = !(var.microsoft_defender_enabled && !var.log_analytics_workspace_enabled)
│     ├────────────────
│     │ var.log_analytics_workspace_enabled is false
│     │ var.microsoft_defender_enabled is true
│
│ Enabling Microsoft Defender requires that `log_analytics_workspace_enabled`
│ be set to true.
╵ 
```

`log_analytics_workspace_enabled = true` will also deploy the Container Insights solution, but I don't have the permission to do that.

I will ask the global admin to deploy the Container Insights solution. Then, with the resource id I can prevent a new solution to be provisioned.

In the meanwhile, is Microsoft Defender really requiring the solution to be deployed? If not, then a new variable should be introduced next to `log_analytics_workspace_enabled`, e.g. `log_analytics_workspace_solution_enabled`.

**Comment by lonegunmanb** [comment] 2023-03-28 02:35
> In the meanwhile, is Microsoft Defender really requiring the solution to be deployed? If not, then a new variable should be introduced next to log_analytics_workspace_enabled, e.g. log_analytics_workspace_solution_enabled.

Hi @cveld, here's [`azurerm_kubernetes_cluster`'s document](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster#log_analytics_workspace_id)

>A microsoft_defender block supports the following:

>[log_analytics_workspace_id](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster#log_analytics_workspace_id) - (Required) Specifies the ID of the Log Analytics Workspace where the audit logs collected by Microsoft Defender should be sent to.

Yes, a log analytics workspace is required.

**Comment by lonegunmanb** [comment] 2023-03-28 02:37
> `oms_agent` is also a property that is set by a deploy if not exists policy I believe. How can prevent change detection on this property? Also `azure_policy_enabled` is changed from `true` to `false` surprisingly.

Could you please give us a minimum sample code that could reproduce this issue on your side so we can test and verify it? Thanks!

**Comment by lonegunmanb** [comment] 2023-03-28 04:59
As for `kubernetes_version` drift issue, I've opened pr #336 to solve it, would you please give it a review @cveld? Thanks.

**Comment by cveld** [comment] 2023-04-02 15:06
> Yes, a log analytics workspace is required.

True, but is also the Container Insights solution required?

Actually, now I take a better look at the proposed change as soon as I enable defender:

` ~ microsoft_defender {
          ~ log_analytics_workspace_id = "/subscriptions/redacted/resourcegroups/DefaultResourceGroup-WEU/providers/Microsoft.OperationalInsights/workspaces/DefaultWorkspace-redacted-WEU" -> "/subscriptions/anothersubscription/resourceGroups/rg-log-analytics-workspace-prd/providers/Microsoft.OperationalInsights/workspaces/log-analytics-workspace"      
        }`

**Comment by lonegunmanb** [comment] 2023-04-10 03:13
>but is also the Container Insights solution required?

Yes, it's [supported](https://github.com/Azure/terraform-azurerm-aks/blob/main/main.tf#L549-L563) by default @cveld.

**Closed** 2023-04-12 15:45 UTC
Labels: bug
