### ISSUE TITLE
node_os_channel_upgrade not actually doing anything

### ISSUE THREAD

**Issue by tdevopsottawa** [Azure/terraform-azurerm-aks#487] opened 2023-12-12 18:32 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Greenfield/Brownfield provisioning

brownfield

### Terraform Version

1.4.0

### Module Version

7.5.0

### AzureRM Provider Version

3.69.0

### Affected Resource(s)/Data Source(s)

azurerm_kubernetes_cluster

### Terraform Configuration Files

```hcl
module "aks_cluster" {
  source  = "Azure/aks/azurerm"
  version = "7.5.0"

  cluster_name               = var.cluster_name
  kubernetes_version         = var.kubernetes_version
  orchestrator_version       = var.orchestrator_version
  prefix                     = var.prefix
  resource_group_name        = var.resource_group_name
  location                   = var.az_location
  enable_auto_scaling        = var.enable_auto_scaling
  azure_policy_enabled       = true
  maintenance_window         = var.maintenance_window
  maintenance_window_node_os = var.maintenance_window_node_os
  node_os_channel_upgrade    = var.node_os_channel_upgrade
  disk_encryption_set_id     = var.disk_encryption_set_id
  oidc_issuer_enabled        = true

  private_cluster_enabled       = var.private_cluster_enabled
  private_dns_zone_id           = var.custom_dns_zone
  public_network_access_enabled = var.public_network_access_enabled

  admin_username = var.admin_username
  public_ssh_key = var.public_ssh_key

  identity_ids  = tolist([var.managed_identity_id])
  identity_type = "UserAssigned"

  network_plugin                 = "kubenet"
  net_profile_outbound_type      = var.outbound_type
  net_profile_pod_cidr           = var.net_profile_pod_cidr
  net_profile_service_cidr       = var.net_profile_service_cidr
  net_profile_dns_service_ip     = var.net_profile_dns_service_ip

  role_based_access_control_enabled = true
  rbac_aad_managed                  = true
  rbac_aad_admin_group_object_ids   = var.admin_group_object_id

  agents_pool_name          = "agentpool"
  agents_max_count          = var.max_node_count
  agents_min_count          = var.min_node_count
  agents_size               = var.vm_size
  agents_count              = var.agents_count
  agents_availability_zones = var.agents_availability_zones
  os_disk_type              = var.os_disk_type
  os_disk_size_gb           = var.os_disk_size_gb
  vnet_subnet_id            = var.subnet_id

  log_analytics_workspace_enabled             = true
  cluster_log_analytics_workspace_name        = var.log_analytics_workspace_name
  log_analytics_workspace_resource_group_name = var.resource_group_name
  log_analytics_workspace_sku                 = "PerGB2018"
  log_retention_in_days                       = 30
  log_analytics_workspace                     = var.log_analytics_existing_workspace

  ingress_application_gateway_enabled   = var.use_ingress_application_gateway
  ingress_application_gateway_name      = var.ingress_application_gateway_name
  ingress_application_gateway_id        = var.ingress_application_gateway_existing_id
  ingress_application_gateway_subnet_id = var.ingress_application_gateway_subnet_id

  workload_identity_enabled = var.enable_workload_identity

  node_pools = var.additional_node_groups
}
```

### tfvars variables values

```hcl
Almost all are too sensitive, but these are the relevant ones

  maintenance_window_node_os = {
    day_of_week = "Tuesday"
    duration    = "4"
    frequency   = "Weekly"
    interval    = "4"
    start_date  = "2023-12-12T18:15:00Z"
    start_time  = "18:20"
    not_allowed = [
      {
        start = "2024-11-25T00:00:00Z"
        end   = "2024-12-04T23:59:59Z"
      },
      {
        start = "2024-12-15T00:00:00Z"
        end   = "2025-01-02T23:59:59Z"
      },
    ]
  }

node_os_channel_upgrade = "NodeImage"
```

### Debug Output/Panic Output

```shell
(I have an enormous state with thousands of resources and hundreds of confidential things in it).
```

### Expected Behaviour

Auto update policy created and node OS updates start happening.

### Actual Behaviour

Nothing happened. When the time specified in the Terraform came to pass, no upgrade was done. Furthermore, debug commands on the cluster show that no upgrade policies were applied despite Terraform applying.

```
$ az aks show --resource-group <redacted> --name <redacted> --query "autoUpgradeProfile"
The behavior of this command has been altered by the following extension: aks-preview
{
  "upgradeChannel": "none"
}
```

```
$ az aks maintenanceconfiguration show --resource-group <redacted> --cluster-name <redacted> --name aksManagedNodeOSUpgradeSchedule
resource_group_name: redacted, cluster_name: redacted, config_name: aksManagedNodeOSUpgradeSchedule
{
  "id": "/subscriptions/redacted/resourceGroups/redacted/providers/Microsoft.ContainerService/managedClusters/redacted/maintenanceConfigurations/aksManagedNodeOSUpgradeSchedule",
  "name": "aksManagedNodeOSUpgradeSchedule",
  "notAllowedTime": null,
  "resourceGroup": "redacted",
  "systemData": null,
  "timeInWeek": null,
  "type": null
}
```

### Steps to Reproduce

terraform apply

**Comment by zioproto** [comment] 2023-12-13 19:04
Hello @tdevopsottawa , thanks for opening this issue.

I understand you are not setting `var.automatic_channel_upgrade` that will be `null` by default:

https://github.com/Azure/terraform-azurerm-aks/blob/3178d8ce96e33ba1647efba900f174821e4145a1/variables.tf#L346-L357

This is why you have:
```
{
  "upgradeChannel": "none"
}
```

However according to your code, you should have this output:
```
{
  "nodeOsUpgradeChannel": "NodeImage",
  "upgradeChannel": "none"
}
```
We need to understand why you don't have `nodeOsUpgradeChannel`.

Can you confirm you registered the `NodeOsUpgradeChannelPreview` feature flag ?

https://learn.microsoft.com/en-us/azure/aks/auto-upgrade-node-os-image#register-nodeosupgradechannelpreview

You should have the following output:
```
% az feature show --namespace "Microsoft.ContainerService" --name "NodeOsUpgradeChannelPreview"

Name                                                    RegistrationState
------------------------------------------------------  -------------------
Microsoft.ContainerService/NodeOsUpgradeChannelPreview  Registered
```

**Comment by zioproto** [comment] 2023-12-13 19:13
@tdevopsottawa let me check with @kaarthis what is the status of this.

The feature should be GA according to this issue: https://github.com/Azure/AKS/issues/2181

However the steps to register the preview feature `NodeOsUpgradeChannelPreview` are still in the docs.

**Comment by zioproto** [comment] 2023-12-13 19:21
@tdevopsottawa I also tested the schedule, and I actually see a schedule:
```
az aks maintenanceconfiguration show --cluster-name <redacted> -g <redacted> --name aksManagedNodeOSUpgradeSchedule -o json

The behavior of this command has been altered by the following extension: aks-preview
resource_group_name: redacted, cluster_name: redacted, config_name: aksManagedNodeOSUpgradeSchedule
{
  "id": "/subscriptions/redacted/resourceGroups/redacted/providers/Microsoft.ContainerService/managedClusters/redacted/maintenanceConfigurations/aksManagedNodeOSUpgradeSchedule",
  "maintenanceWindow": {
    "durationHours": 4,
    "notAllowedDates": [
      {
        "end": "2025-01-02",
        "start": "2024-12-15"
      },
      {
        "end": "2024-12-04",
        "start": "2024-11-25"
      }
    ],
    "schedule": {
      "absoluteMonthly": null,
      "daily": null,
      "relativeMonthly": null,
      "weekly": {
        "dayOfWeek": "Tuesday",
        "intervalWeeks": 4
      }
    },
    "startDate": "2023-12-14",
    "startTime": "18:20",
    "utcOffset": "+00:00"
  },
  "name": "aksManagedNodeOSUpgradeSchedule",
  "notAllowedTime": null,
  "resourceGroup": "redacted",
  "systemData": null,
  "timeInWeek": null,
  "type": null
}
```

**Comment by zioproto** [comment] 2023-12-13 20:34
@tdevopsottawa my understanding is that only the `SecurityPatch` channel is in preview. In case you had the preview feature enabled previously could you please do this:

```
az feature unregister --namespace "Microsoft.ContainerService" --name "NodeOsUpgradeChannelPreview"
# wait for Unregistered state
az feature show --namespace "Microsoft.ContainerService" --name "NodeOsUpgradeChannelPreview"
# register the provider again
az provider register -n Microsoft.ContainerService'
```

I tried to reproduce with your same terraform and provider version, but I was not able to have your same output for `aksManagedNodeOSUpgradeSchedule`.

**Comment by lonegunmanb** [comment] 2023-12-15 09:12
@tdevopsottawa Thanks for opening this issue, would you please provide us more details so we can reproduce this issue on our side? Thanks!

**Comment by tdevopsottawa** [comment] 2023-12-19 16:46
I tried to unregister and re-register the preview feature and apply terraform again but I could not get it to work. aksManagedNodeOSUpgradeSchedule continues to be empty despite Terraform applying a change.

**Comment by zioproto** [comment] 2023-12-19 20:04
@tdevopsottawa can you reproduce this issue in your subscription also using Azure CLI ? I am trying to understand if this is something specific affecting your subscription or if this is something that can be reproduced only using Terraform.

Have you tried also opening a support ticket to Azure Support ?

**Comment by tdevopsottawa** [comment] 2023-12-20 20:29
I just tested adding the configuration manually with az cli commands (as outlined in https://learn.microsoft.com/en-us/azure/aks/planned-maintenance) instead of using Terraform and I'm having the same problem

**Comment by zioproto** [comment] 2023-12-21 07:04
@tdevopsottawa Thanks testing with Azure CLI. This seems to be a product issue related to your specific subscription. Could you please follow up with Microsoft support ? I don't think this is actionable anymore for us maintaining the Terraform module. Please let us know if we can close the issue. thanks

**Comment by zioproto** [comment] 2023-12-27 11:01
@tdevopsottawa please could you let us know if:

*  is there any Terraform module or provider change that would prevent this issue from happening again ?
*  Did you sort out if this is a problem scoped to a specific Azure subscription of yours ? 
* Any relevant update from Microsoft support ?

Let us know if there is anything actionable next step, or I suggest to close this issue because we can't reproduce the problem on our side.

Thanks

**Comment by lonegunmanb** [comment] 2024-02-19 06:45
I'm closing this issue since no response from the user, please feel free to reopen it if you have any further information to share with us @tdevopsottawa

**Closed by lonegunmanb** 2024-02-19 06:45 UTC
Labels: bug, waiting-response
