### ISSUE TITLE
microsoft_defender_enabled cannot use the default log analytics workspace created by Cloud Defender

### ISSUE THREAD

**Issue by tanvp112** [Azure/terraform-azurerm-aks#495] opened 2024-01-09 10:31 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Greenfield/Brownfield provisioning

brownfield

### Terraform Version

1.6.6

### Module Version

7.5.0

### AzureRM Provider Version

3.8.0

### Affected Resource(s)/Data Source(s)

azurerm_kubernetes_cluster

### Terraform Configuration Files

```hcl
https://github.com/Azure/terraform-azurerm-aks/blob/main/main.tf#L428

dynamic "microsoft_defender" {
  for_each = var.microsoft_defender_enabled ? ["microsoft_defender"] : []
  content {
    log_analytics_workspace_id = local.log_analytics_workspace.id
  }
}

When Cloud Defender is used to automate the deployment of Defender Agent to existing clusters previously provisioned using this module; subsequent terraform apply to these clusters will force to remove the Defender due to Cloud Defender created and used the default Log Analytics Workspace.
```

### tfvars variables values

```hcl
NA
```

### Debug Output/Panic Output

```shell
NA
```

### Expected Behaviour

This module should not modify microsoft defender settings added by Cloud Defender service.

Please add [microsoft_defender](https://github.com/Azure/terraform-azurerm-aks/blob/main/main.tf#L428C11-L428C30) to the [ignore_changes here](https://github.com/Azure/terraform-azurerm-aks/blob/main/main.tf#L521)

### Actual Behaviour

This module will attempt to remove the deployed Defender agent.

### Steps to Reproduce

Enable Cloud Defender on the Portal to an existing cluster created by this module, and run terraform plan once Cloud Defender has completed Defender agent deployment.

### Important Factoids

NA

### References

NA

**Comment by zioproto** [comment] 2024-01-09 13:57
Hello @tanvp112 

If I understand correctly the clusters created with this module have a `null` value for the `securityProfile.defender` field:

```
az aks show --name <name> -g <rg> -o json | jq .securityProfile.defender
```

Now you are making some changes in the portal that are changing the `null` value and you have configuration drift.

When you say "Enable Cloud Defender on the Portal to an existing cluster created by this module" are you doing the equivalent of:
```
az aks update --name <name> -g <rg>  --enable-defender
```

Is this correct ? Or you tried to enable it at the subscription level ?
https://learn.microsoft.com/en-us/azure/defender-for-cloud/tutorial-enable-containers-azure#enable-the-defender-for-containers-plan

Related provider issues:
* https://github.com/hashicorp/terraform-provider-azurerm/issues/17663

**Comment by tanvp112** [comment] 2024-01-10 02:32
> If I understand correctly the clusters created with this module have a `null` value for the `securityProfile.defender` field:
> 
> ```
> az aks show --name <name> -g <rg> -o json | jq .securityProfile.defender
> ```
> 

Yes, that's the default.

> Now you are making some changes in the portal that are changing the `null` value and you have configuration drift.
> 
> When you say "Enable Cloud Defender on the Portal to an existing cluster created by this module" are you doing the equivalent of:
> 
> ```
> az aks update --name <name> -g <rg>  --enable-defender
> ```
> 

No, az cli is not used in this case. The defender agent was enabled via the Microsoft Defender for Cloud's recommendations page on the Portal. This way the workspace in the default resource group created by Azure will be use. But due to the way log analytics workspace ID is assigned in the module currently, terraform will attempt to remove the defender.

> Is this correct ? Or you tried to enable it at the subscription level ? https://learn.microsoft.com/en-us/azure/defender-for-cloud/tutorial-enable-containers-azure#enable-the-defender-for-containers-plan
> 

Automatic deployment at subscription level is **not** enabled in this case.

> Related provider issues:
> 
> * [microsoft_defender for `azure_kubernetes_service` can not be disabled hashicorp/terraform-provider-azurerm#17663](https://github.com/hashicorp/terraform-provider-azurerm/issues/17663)

Given this 17663 issue I think it is even more important to add [microsoft_defender](https://github.com/Azure/terraform-azurerm-aks/blob/main/main.tf#L428C11-L428C30) to the [ignore_changes here](https://github.com/Azure/terraform-azurerm-aks/blob/main/main.tf#L521).

**Comment by zioproto** [comment] 2024-01-10 09:09
We need to find a consistent solution thats works in both cases:
* var.microsoft_defender_enabled = true
* var.microsoft_defender_enabled = false

What happens if you set `var.microsoft_defender_enabled = true` and you set also `var.log_analytics_workspace` ? Does it make a problem to add `microsoft_defender` in the `ignore_changes` ?

**Comment by tanvp112** [comment] 2024-01-10 09:58
It wouldn't create any problem, the defender agent will just use the supplied log analytics workspace. But this is not always the case, the [17663](https://github.com/hashicorp/terraform-provider-azurerm/issues/17663) issue has presented different ways to specify log analytics workspace for the agent, this issue has shown what happened when default workspace is used. Because there is no definite way to assign log analytics workspace as well as detecting which way a user might do the assignment, this module should not attempt to track and force change assignment made outside of the module.

**Comment by lonegunmanb** [comment] 2024-01-11 06:41
Hi @tanv112, I've tried to reproduce this issue by the following steps but I failed:

1. Add `microsoft_defender_enabled = true` assignment in `named_cluster` example's `module.aks_cluster_name` block
2. Apply the example
3. Set Microsoft Defender for Containers to "On" and save
4. Try to execute `terraform plan`

I cannot see any config drift. Could you please provide us a minimum example with steps to reproduce the issue you described, so I can study? Thanks!

**Comment by tanvp112** [comment] 2024-01-11 10:57
@zioproto, 

Yes, that's one way you can re-produce the issue.

Note in many environments out there; Cloud Defender is not always enabled upfront, there are many factors around this, eg. switching cloud security tools,  separation of Log Analytics Workspace for cloud defender to the one associated with the cluster etc. 

In short, there are several ways to enable Cloud Defender, if this module insist to have cloud defender use _only_ the log analytics workspace associated with the cluster, then this module is not usable in all scenarios where cloud defender is separately deployed (eg. [17663](https://github.com/hashicorp/terraform-provider-azurerm/issues/17663)).

Currently, I folked a copy of this module and add `microsoft_defender` to the `ignore_changes` - it works perfectly for impacted clusters.

**Comment by zioproto** [comment] 2024-01-12 14:31
I spotted another Terraform state drift, also `azure_policy_enabled` is changed by Microsoft Defender when accepting the recommendations.

```
  # module.aks.azurerm_kubernetes_cluster.main will be updated in-place
  ~ resource "azurerm_kubernetes_cluster" "main" {
      ~ azure_policy_enabled                = true -> false
        id                                  = "/subscriptions/redacted/resourceGroups/aks-spotty/providers/Microsoft.ContainerService/managedClusters/spotty-aks"
        name                                = "spotty-aks"
        tags                                = {}
        # (28 unchanged attributes hidden)

      - microsoft_defender {
          - log_analytics_workspace_id = "/subscriptions/redacted/resourcegroups/DefaultResourceGroup-EUS/providers/Microsoft.OperationalInsights/workspaces/DefaultWorkspace-redacted-EUS" -> null
        }

        # (10 unchanged blocks hidden)
    }
```

This is exactly why I am afraid in adding stuff into `ignore_changes` because the list could become way longer over time.

**Comment by tanvp112** [comment] 2024-01-14 10:56
`This is exactly why I am afraid in adding stuff into ignore_changes because the list could become way longer over time.`

While not all Azure services, such behavior is very common in Azure environment, not to mention breaking changes. That why this module should not attempt to track and force changes made outside of the module by Azure services. Perhaps Azure services want to automate as much as possible to improve user experience - but this approach is anti-pattern to resources that manage by IaC. This module has to accept the fact that it cannot track/force all the possibilities that Azure services can introduce now and the future.

**Comment by zioproto** [comment] 2024-01-26 09:00
So far we can propose the following solution, use this configuration:

```
  azure_policy_enabled              = true
  microsoft_defender_enabled        = true
```

this will not cause configuration drift.

The problem is that Terraform assumption is that all the resources are managed by Terraform, and it tries to reconcile any infrastructure drift.

We are thinking about how to solve this issue in a better way long term, without exploding the ignore list in the lifecycle block. Please hold until we find a good solution.

**Comment by lonegunmanb** [comment] 2024-02-19 07:06
After a deep review I decide to close this issue without putting `microsoft_defender` into `ignore_changes`, the reason is, the users could use all kinds of Azure Policies which could change any attributes of any resources. The root causes of this issue are:

1. IaC works from Shift Left side and Auto Remediation triggered by service like Azure Policy works from Shift Right side, we cannot say which side is right or wrong, but sometimes they just don't get along.
2. Terraform doesn't support user input variables for meta-arguments like `inore_changes`, `create_before_destroy`. It looks like the OpenTofu community [is working on this issue](https://github.com/opentofu/opentofu/issues/1042) but this topic is beyond this issue's scope.

It's not an easy decision, for now the best way is what @tanvp112 has done, make a fork. I can imagine an approach of managing a private fork:

1. Create your own module
2. Use git submodule to add this repo as a submodule in the new repo
3. Use symbolic link to link all `.tf` file from the submodule to the new repo's root folder
4. Create your own [`.override.tf`](https://developer.hashicorp.com/terraform/language/files/override) file to override the meta-arguments you need to customize.

Anyway, thanks @tanvp112 for opening this issue to us. I'll try to create an interesting tool that work with Terraform, which is designed to solve this kind of issue by customizing `.tf` files in module folders download by `terraform init`, you can call `terraform init`, download modules into `.terraform` folder, then use this tool to customize all `.tf` files, then execute `terraform apply`. I'll ping you here once I've finished the demo, and at that time if you're interested in the tool, you're welcomed to give it a try.

**Closed by lonegunmanb** 2024-02-19 07:06 UTC
Labels: bug

**Comment by tanvp112** [comment] 2024-02-20 01:43
@lonegunmanb , it would be my pleasure to try out your proposed solution, please let me know when it is ready for a ride!

**Comment by zioproto** [comment] 2024-11-29 08:24
Please look at this example of the `mapotf` tool that should solve the Microsoft Defender use case:

https://github.com/Azure/mapotf/tree/main/example/customize_aks_ignore_changes
