### ISSUE TITLE
Updating values forces create new resources 

### ISSUE THREAD

**Issue by sshah90** [Azure/terraform-azurerm-aks#85] opened 2021-01-06 18:13 UTC
Hello, This is a very easy module to work with but after deploying AKS cluster but when I try to apply some changes/updates it creates a new cluster. 

After debugging I figure out that there are some values that are by default set up as "null" which causing this re-creation.

Check Below screenshots from my plan

![Screen Shot 2021-01-06 at 1 01 43 PM](https://user-images.githubusercontent.com/26821376/103804298-ddc7d000-501f-11eb-881c-add1a06ae7ea.png)

As you can see `node_taints` (this var needs to be added in the module), `agents_availability_zones` should be `[]` but as its default value is null so if a user doesn't provide it so resource recreate aks.

If we don't set auto_scaling for the default node pool then max and min pod should be `0` not null and the same goes with `network_policy` as well.

Please update/add the following variable's default values.

- network_policy = "azure"
- agents_availability_zones = []
- agents_max_count = 0 (also change `0` [here](https://github.com/Azure/terraform-azurerm-aks/blob/master/main.tf#L36-L37))
- agents_min_count = 0 
- node_taints= [] (add new var in default_node_pool block)

**Comment by yupwei68** [comment] 2021-01-20 03:05
Hi @sshah90 , thanks for opening this issue. Would you provide your Azurerm version, terraform version, your hcl script and reproducing steps to help to reproduce this problem? Sorry that I can not reproduce this problem now.

**Comment by yupwei68** [comment] 2021-05-21 08:20
Hi @sshah90 ,sorry that I could not reproduce your error. 
I tested with the script below, and I `terraform apply`, and then `terraform plan`. It shows no changes.

```
module "aks" {
  source                         = "Azure/aks/azurerm"
  prefix                         = "prefix"
  resource_group_name            = azurerm_resource_group.test.name
  enable_log_analytics_workspace = false
  enable_kube_dashboard          = false
  net_profile_pod_cidr           = "10.1.0.0/16"
  depends_on                     = [azurerm_resource_group.test]
}
```

**Comment by sshah90** [comment] 2021-05-21 15:42
Hi @yupwei68, sorry for the late reply.

I have my code somewhere but not able to find it at this moment.

I will try to reproduce this issue over the weekend and let u know.

**Comment by lonegunmanb** [comment] 2022-09-30 11:23
I'm closing this issue due to no further response. Please feel free to reopen this issue if you can reproduce this issue with the latest version, thanks for your understanding @sshah90 .

**Closed by lonegunmanb** 2022-09-30 11:23 UTC
