### ISSUE TITLE
Support the `ingress_application_gateway` addon

### ISSUE THREAD

**Issue by wjam-hanzo** [Azure/terraform-azurerm-aks#115] opened 2021-07-23 10:23 UTC
There is currently no support for enabling the `ingress_application_gateway` addon on the AKS cluster. Please add support for enabling this addon.

**Comment by jcorioland** [comment] 2022-01-19 07:52
@davidkarlsen hi, I am an external contributor to this repo, not actively working on it on my side. But, the team who owns this confirmed to me the module is still active.

**Comment by davidkarlsen** [comment] 2022-01-19 08:17
> @davidkarlsen hi, I am an external contributor to this repo, not actively working on it on my side. But, the team who owns this confirmed to me the module is still active.

OK, good to know, on the other side, there seems to be no activity on the PRs or releases.

**Comment by davidkarlsen** [comment] 2022-01-26 19:42
I think this issue can be closed as the PR has been merged now.

**Comment by lonegunmanb** [comment] 2022-01-27 01:51
Hi @davidkarlsen , since we're still haven't a new release yet, do you think it's ok to close this issue now?

**Comment by davidkarlsen** [comment] 2022-01-27 02:02
I guess that depends on your policy - if you close issues when they are merged, or tagged? It has been merged.
Which brings us to release policy - what criteria brings those along?

**Closed** 2022-09-30 11:13 UTC
