### ISSUE TITLE
Changing sku_tier forces replacement

### ISSUE THREAD

**Issue by nxf5025** [Azure/terraform-azurerm-aks#123] opened 2021-09-10 22:37 UTC
Changing the sku_tier from Paid to Free forces a full rebuild of the cluster. If this can be done via the Azure CLI without a rebuild why should terraform?

Any insight would be helpful.

**Comment by wondersd** [comment] 2021-09-20 14:50
@nxf5025 rebuilding resources when attributes are changed is controlled by the provider implementation, in this case [azurerm](https://github.com/hashicorp/terraform-provider-azurerm)

It looks like the original sku support did force a new resource to be created when modifying the sku type.

https://github.com/hashicorp/terraform-provider-azurerm/commit/5348f2a15456acffa19dde96b39487b12263b322

According to the comments, at the time it was not possible to change this after creation.

In the most recent version of the provider, this is no longer true.

https://github.com/hashicorp/terraform-provider-azurerm/blob/main/internal/services/containers/kubernetes_cluster_resource.go#L731-L739

`ForceNew: true` was removed.

Couldnt find what release that was changed but the most recent or somewhere near there should allow the sku to be changed like via the cli

**Comment by lonegunmanb** [comment] 2022-09-30 11:55
I'm closing this issue due to no further response, and I've tested and verified that changing `sku_tier` won't cause a force new anymore. Please feel free to reopen this issue if you can reproduce with the latest module and provider, thanks for your understanding @nxf5025.

**Closed by lonegunmanb** 2022-09-30 11:55 UTC
